CREATE TABLE USERS
(id serial PRIMARY KEY,
 name VARCHAR(30) NOT NULL UNIQUE,
 pass VARCHAR(300) NOT NULL,
 last_login TIMESTAMP NOT NULL,
 api_key VARCHAR(50),
 admin BOOLEAN DEFAULT FALSE
 );

CREATE TABLE TSDATA
(id serial PRIMARY KEY,
 name VARCHAR(30) NOT NULL UNIQUE,
 freq SMALLINT NOT NULL
 );

CREATE TABLE TSDATA_CHILDREN
(id serial PRIMARY KEY,
 parent_name VARCHAR(30) REFERENCES TSDATA(name) NOT NULL,
 name VARCHAR(30) NOT NULL,
 UNIQUE (parent_name, name)
 );

CREATE TABLE ALLOWED_DATA
(id serial PRIMARY KEY,
 user_name VARCHAR(30) REFERENCES USERS(name) NOT NULL,
 data_name VARCHAR(30),
 d_child_name VARCHAR(30),
 FOREIGN KEY (data_name, d_child_name)
 REFERENCES TSDATA_CHILDREN(parent_name, name)
 );

CREATE TABLE EXPERIENCE
(id serial PRIMARY KEY,
 user_id VARCHAR(30) REFERENCES USERS(name) NOT NULL,
 date TIMESTAMP NOT NULL,
 data_key VARCHAR(30) NOT NULL,
 param jsonb NOT NULL
 );

CREATE TABLE LOG
(id serial PRIMARY KEY,
 user_name VARCHAR(30) REFERENCES USERS(name) NOT NULL,
 date TIMESTAMP NOT NULL,
 IP VARCHAR(40),
 query SMALLINT NOT NULL,
 success SMALLINT NOT NULL
 );

CREATE TABLE TEST
(id serial PRIMARY KEY,
 name varchar(30));
